#!/usr/bin/ruby
require "#{File.dirname(__FILE__)}/shared/util"

module Program
   extend self
   VERSION="1.0.0"
   USAGE_MESSAGE="
usage:
      #{Util::getScriptName} \"page title\" <sequence-num>

      * \"page title\" - The title of the new page. [required]

      * <sequence-num> - The user defined sequence. [optional]
                         This is set only when you know of an item you want to be first, or last. 
                         (99 is last. 0 is first.)
"
   def checkArgs
      if (ARGV.length > 0 && ARGV[0]=="--version")
         puts "#{Util::getScriptName} v#{VERSION}"
         exit 0
      elsif ARGV.length >0 && ARGV.length <=2
         return true
      else
         puts USAGE_MESSAGE
         exit 1
      end
   end

   def execute
      if (checkArgs)
         site_dir=Util::getSiteDir
         puts Util::getCanonicalFileSystemName(ARGV[0])
         puts Util::getCanonicalTitle(ARGV[0])
      end
   end
end
MyDerived::foo
Program::execute