# Welcome to Jekyll ! 
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is * NOT * reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jason C Daniels.net
email:
description: > # this means to ignore newlines until "baseurl:"
  This is my little home on the internet. I post about various subjects at infrequent times.
baseurl: ""# the subpath of your site, e.g. /blog
url: "http://jason-c-daniels.net" # the base hostname & protocol for your site

mastodon_username: JasonCDaniels
twitter_username: JasonCDaniels
github_username: jason-c-daniels
linkedin_username: jasondaniels55347
#google_plus_username: jason.c.daniels@gmail.com
#facebook_username:
#dribbble_username:

timezone: US/Central
encoding: utf-8        #explicit encoding, to prevent future changes to jekyll from hosing us up.

# Build settings
markdown: kramdown

#plugins:
#  - jekyll-toc